kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: product-claim
  namespace: product
  finallizers: null
spec:
  storageClassName: product-nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
