apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hyunjun1325/frontend:79
        ports:
        - containerPort: 8080


