# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-nodeport
#   namespace: product
# spec:
#   type: NodePort
#   ports:
#   - port: 8080 #svc 조회했을때 clusterIP:Port  index.js에서 listening하는 포트
#     targetPort: 8080 #endpoints(컨테이너IP:Port)
#     nodePort: 30003 #외부 IP에서 접근할 포트
#   selector:
#     app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: product
  annotations:
   metallb.universe.tf/address-pool: 
spec:
  type: LoadBalancer
  ports:
  - port: 8080 #svc 조회했을때 clusterIP:Port  index.js에서 listening하는 포트
    targetPort: 8080 #endpoints(컨테이너IP:Port)
  selector:
    app: frontend


