apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: mariadb
        image: mysql:8.0.33
        ports:
        - containerPort: 8080
        volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: product-pvc
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: product-creds
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-creds
              key: password
        - name: MYSQL_DATABASE
          value: "product"
      volumes:
        - name: product-pvc
          persistentVolumeClaim:
            claimName: product-claim
