apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: product
  name: backend-svc
  namespace: product
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend