apiVersion: v1
kind: Service
metadata:
  name: product-mysql-service
  namespace: product
spec:
  selector:
    app: mysql
  ports:
      # 기본적으로 그리고 편의상 `targetPort` 는 `port` 필드와 동일한 값으로 설정된다.
    - port: 8080
      targetPort: 3306
      # 선택적 필드
